storeItemList:
  - id: '16956393582480.25831357886906736'
    name: discoverData
    value: {}
    valueType: object
    initialValue: {}
    version: 1
    parentPageId: '1'
metadata:
  favicon: ''
  code: |-
    <style>
      .detailCard movieDetail {
        flex: 1;
        width: 2000;
        height: 1000;
      }
    </style>
  title: New app
  description: ''
appSettings:
  properties:
    defaultData: '{}'
  actions:
    appLoad: []
    appData: []
  gridVersion: 2
internalType: project
